title: hyojun note about web
email: chlgkwk123@nate.com
description: |
  웹 프로그래밍 연습장입니다.
baseurl: ''

timezone: Asia/Seoul

repository: hyojun123/hyojun123.github.io

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: '/page/:num/'

collections:
  authors:
    output: true
    permalink: /authors/:path
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]
url: https://hyojun123.github.io
keep_files: [assets, files]
github: [metadata]
# iolo's custom
author: chlgkwk123@nate.com
image: '/assets/images/default_blog_cover.jpg'
asset_url: /assets
#asset_url: //meta-kage.kakaocdn.net/dn/osa/blog/assets
#asset_url: //t1.daumcdn.net/osa/blog/assets
#google_analytics:
#  ua: 'UA-72007721-1'
facebook:
  app_id: '1204347326263800'
  username: profile.php?id=100007371457483
#twitter:
#  username: kakaodev
#google_plus:
#  username: kakaodev
github_url:
  username: hyojun123/hyojun123.github.io
